# -*- coding: utf-8 -*-
"""Oficina_3_1_evelynsantos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1msQCqKJ91xBPhanHCMMrYHu7B14k7i_K

# Oficina Aula 3.1
Durante a aula você aprendeu que conhecer a distribuição de uma variável é importante para caracterizar o seu comportamento e encontrar padrões presentes nos dados. Agora é hora de exercitar o que você aprendeu!

Nesta oficina, continue explorando os dados imobiliários que você acompanhou durante a aula. Crie um Jupyter Notebook e responda cada questão com código em uma célula.

1.   Importe as bibliotecas pandas, matplotlib e seaborn e use a palavra mágica inline para exibir as visualizações no notebook. Carregue os dados em um DataFrame. Os dados estão disponibilizados no link: dados. Você pode carregar os dados pela URI ou salvar em sua máquina e carregá-los localmente.
1.   Crie uma visualização que mostre a distribuição dos valores de aluguel, ' rent amount (monetario ) ',dos imóveis. Pode utilizar o gráfico que você julgar mais adequado. Qual faixa de valores de aluguel é mais comum?
1.   Crie uma visualização que mostre a distribuição dos valores de seguro contra incêndio, 'fire insurance (R$)', dos imóveis. Existem valores incomuns?

# 1  Importe as bibliotecas pandas/ Carregue os dados em um DataFrame
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

df = pd.read_csv('https://raw.githubusercontent.com/evelynsantos/Data-visualization/main/houses_to_rent_v3.txt')
df.head()

"""# 2 visualização distribuição de aluguel do dataset"""

plt.figure(figsize=(8, 4))
plt.title('Distribuição de aluguel de imóveis')
plt.ylabel('Densidade de probabilidade')
sns.distplot(df['rent amount (R$)'], kde = True)
plt.show()

plt.hist(df['rent amount (R$)'],bins=500)
plt.show()

"""A faixa de aluguel mais comum é entre R$$ 1.000 e  R$ 2.500

# 3 visualização de distribuição de seguro contra incêndio
"""

plt.figure(figsize=(8, 4))
plt. title('Distribuição de seguro contra incêndio')
sns.distplot(df['fire insurance (R$)'])
plt.show()

"""Valores mais incomuns são acima de R$100"""