# -*- coding: utf-8 -*-
"""Oficina_4_2_evelynsantos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SW7M0Jse0kCPJg2bS-50jzgXnQz5ioYa

# Oficina Aula 4.2
Nesta oficina você irá analisar distribuições conjuntas de um conjunto de dados sobre carros. Esse conjunto de dados contém informações sobre: consumo de galão de combustível por milha (miles per galon, mpg), número de cilindros, cilindrada, cavalos de potência, peso, aceleração, ano do modelo, país de origem e nome do carro. Esse conjunto de dados chama-se “mpg” e é bastante famoso em estatística, sendo disponibilizado diretamente pela biblioteca seaborn sem a necessidade de baixar os dados para a sua máquina. Crie um Jupyter Notebook para responder às questões.

1. Importe as bibliotecas pandas, matplotlib e seaborn e use a palavra mágica inline para exibir as visualizações no notebook. Carregue os dados em um DataFrame. Os dados podem ser carregados pelo seaborn utilizando a função load_dataset(‘mpg’).
1. Crie uma visualização que mostre a distribuição conjunta de todas as variáveis quantitativas, diferenciando pelo país de origem (‘origin’). Quais variáveis possuem uma maior correlação?
1. Sobre a visualização da questão 2, é possível distinguir o país de origem a partir da distribuição de uma variável? E de uma distribuição conjunta?
1. Escolha uma distribuição conjunta em que as variáveis estejam fortemente correlacionadas e crie um gráfico que permita analisar a distribuição conjunta, a reta de regressão e as distribuições marginais.

# 1  Importe as bibliotecas pandas/ Carregue os dados em um DataFrame
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline 
sns.set(style='darkgrid')

df = sns.load_dataset('mpg')
df.sample(10)

"""# 2 visualização distribuição de aluguel do dataset"""

sns.pairplot(df, hue='origin')

sns.pairplot(df, kind='reg')

"""Observa-se através dos gráficos gerado acima tanto da distribuição conjunta quanto dos gráficos com dados dispersos (visualização melhorada para reta de regressão par a par), que as variáveis que possuem maior correlação positiva são:
*   horsepower / displacement
*   displacement / weight
e as que possuem maior correlação negativa são:
*   horsepower x acceleration
*   mpg x horsepower

# 3 distinção de países de origem

a) É possível distinguir o país de origem a partir da distribuição de uma variável passando por parametro a matriz 'origin' gerando a legenda de origem colorida

b) Também é possível distinguir através da distribuição conjunta onde a função pairplot faz a exibição no gráfico geral

Melhores visualizações podem ser obtidas através do gráfico:
"""

plt.figure(figsize=(8, 8))
plt.title('Distribuição de pesos do carro x país de origem')
sns.kdeplot(df['weight'], shade=True, hue=df['origin'])
plt.show()

"""# 4 distribuição conjunta em que as variáveis estejam fortemente correlacionadas"""

sns.jointplot(x='weight' , y='horsepower', kind='reg', data=df);